### ISSUE TITLE
error VisualCode couldn't start client HTMLHint

### ISSUE THREAD

**Issue by oxkr73** [microsoft/vscode-htmlhint#64]
VCS v. 1.38 error on starting HTMLhint.
OS: Windows 10

**Comment by oxkr73** [comment]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

The error is:
[Error - 9:50:12] Starting client failed
Error: spawn C:\Users\ssanrama\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by OttoAnderssonHbg** [comment]
Had the same problem. Cleared out my workspace and it worked again.
