### ISSUE TITLE
Development mode crashes the server repeatedly

### ISSUE THREAD

**Issue by phoenixeliot** [microsoft/vscode-htmlhint#87]
When I try to run the server and open an extension debugging window via f5, I get this error repeatedly in the console from `extensionHostProcess.js`:
```
rejected promise not handled within 1 second: Error: Channel has been closed

stack trace: Error: Channel has been closed
    at m.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:809:372)
    at m.append (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:808:938)
    at m.append (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:900:249)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:809:937
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

And this message in the testing window: 
![Uploading Screen Shot 2020-12-26 at 6.54.40 PM.png…]()

Is there anything special beyond the instructions in the README.md that I need to do to run this extension in development mode?

This is on VS Code version `1.52.1`

**Comment by mike-kaufman** [comment]
IIRC, to debug the "server", you need to:

1. open one vs code instance on htmlhint (`code ./htmlhint`), and a second vs code instance in htmlhint-server (`code ./htmlhint-server`)
1. build & "install" the server: on command-line  `npm run compile` in `htmlhint-server` directory
2. build the extension: on command-line,  `npm run compile` in `htmlhint` directory
3. launch a debug instance with the extenion active:  from the "htmlhint" vs code instance, launch the "Launch Extension" debug confugration
4. Attach to the the htmlhint-server:  From the htmlhint-server vs code instance, launch the  "Attach" debug configuration
